### ISSUE TITLE
내 지갑 - 상세검색 UI

### ISSUE THREAD

**Issue by remypark** [Jerome-bel/pxproject_front#16]
내지갑 - 상세검색 UI 
제대로 출력되지 않고 있습니다.

![image](https://user-images.githubusercontent.com/54258306/66727083-f3c7fe80-ee77-11e9-90b7-334c85d047f9.png)

**Comment by tae-at-fifteenh** [comment]
@remypark 
내 지갑페이지에서만 일어나는 문제인가요?
거래소와 내지갑 상세검색 둘다 같은 UI를 사용하고있거든요 

혹시 맥인가요?..맥 환경은 재현이 불가한 상태입니다 @ryan-at-fifteenh

**Comment by remypark** [comment]
> @remypark
> 내 지갑페이지에서만 일어나는 문제인가요?
> 거래소와 내지갑 상세검색 둘다 같은 UI를 사용하고있거든요
> 
> 혹시 맥인가요?..맥 환경은 재현이 불가한 상태입니다 @ryan-at-fifteenh

맥이 맞구요. 지금은 fix 되어있는 상태입니다.
맥에서 재현이 불가능하지 않습니다.
