### ISSUE TITLE
내자산 메인 컨텐츠 갯수 이슈

### ISSUE THREAD

**Issue by remypark** [Jerome-bel/pxproject_front#18]
1600 해상도 이하에서 아이템이 출력되는 갯수를
가로로 6개 -> 4개까지로 조절 부탁드립니다.
4개씩 3줄로 변경

/02mywallet_01index.html#

**Comment by ryan-at-fifteenh** [comment]
1920 디자인을 기준하여 작업하였으므로 해당 이슈는 대응이 어렵습니다.

**Comment by remypark** [comment]
내부 진행으로 변경

**Comment by Jerome-bel** [comment]
일괄적으로 4개까지 표시하는 걸로 변경
