### ISSUE TITLE
(공통)상품썸네일의 마우스 오버시 효과

### ISSUE THREAD

**Issue by remypark** [Jerome-bel/pxproject_front#5]
상품썸네일에 마우스 오버시 그래프가 출력되는(이미지로) 형태 구현이 필요합니다.
순위태그,그래프,텍스트들은 이미지로 export 하였고
blur 효과를 가진 백그라운드는 코딩으로 개발 부탁드립니다.

zeplin 상의 css 코드
.Combined-Shape {
  width: 280px;
  height: 259px;
  border-radius: 5px;
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
  background-color: rgba(0, 0, 0, 0.5);
}

![image](https://user-images.githubusercontent.com/54258306/66725772-e73fa800-ee6f-11e9-8335-242bd7cad067.png)

**Comment by ryan-at-fifteenh** [comment]
착수당시 존재하지 않았던 항목이며, 처리에 1시간정도 소요될 예정입니다.
현재 존재하는 수정가능사항들을 처리하기 위해 처리한다면 금일 내 처리가 어려우며, 협의가 필요합니다.

**Comment by remypark** [comment]
> 착수당시 존재하지 않았던 항목이며, 처리에 1시간정도 소요될 예정입니다.
> 현재 존재하는 수정가능사항들을 처리하기 위해 처리한다면 금일 내 처리가 어려우며, 협의가 필요합니다.

해당화면은 최초 전달시에도 존재했던 화면입니다. 금일 중으로 해주실 필요는 없고 진행만 해주시면 됩니다.
